---

- name: Install and set up grafana on Ubuntu
  hosts: Ubuntusrv
  become: yes
  gather_facts: False
  tasks:

  - name: Update apt repo and cache on all Ubuntu box
    apt: 
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Install required packages 
    apt:
      name:
        - gnupg2
        - curl
        - software-properties-common

  - name: Add the Grafana GPG key
    shell:
      curl https://packages.grafana.com/gpg.key | sudo apt key add add-repository "deb https://packages.grafana.com/oss/deb stable main"
    args:
      warn: no

  - name: Install the grafana package
    apt:
      name: grafana
      state: present
      update_cache: yes
    notift: Start and Enable Nginx

   
